In [1]:
import numpy as np
import pandas as pd

In [2]:
demographic = pd.read_csv('demographic.csv')
labs = pd.read_csv('labs.csv')
quest = pd.read_csv('questionnaire.csv')
exam = pd.read_csv('examination.csv')
diet = pd.read_csv('diet.csv')

In [4]:
quest = quest[['SEQN','MCQ160B','MCQ160C','MCQ160E','MCQ160F']]
quest.dropna(axis=0, inplace=True)
df1 = quest.merge(demographic, on='SEQN', how='left')
df2 = df1.merge(labs, on='SEQN', how='left')
df3 = df2.merge(exam, on='SEQN', how='left')
df = df3.merge(diet, on='SEQN', how='left')

def conditions(s):
    if (s['MCQ160B'] == 1) or (s['MCQ160C'] == 1) or (s['MCQ160E'] ==1) or (s['MCQ160F']==1):
        return 1
    else:
        return 0

df['target'] = df.apply(conditions, axis=1)
df['diastolic-BP'] = df[['BPXDI1', 'BPXDI2','BPXDI3']].mean(axis=1)
df['systolic-BP'] = df[['BPXSY1','BPXSY2','BPXSY3']].mean(axis=1)
df_final=df[['SEQN','RIDAGEYR','diastolic-BP','LBDHDDSI','DR1TKCAL','LBDNENO','systolic-BP','DR1TCALC','LBDMONO','LBDLYMNO','LBDTCSI','LBXSUA','LBXSATSI','LBXSASSI','LBDEONO','LBDSTPSI','LBDSALSI','LBXSTB','LBXHGB','LBXHCT','LBXRBCSI','LBXMCVSI','LBXMCHSI','LBXMC','LBXWBCSI','LBDSIRSI','LBXPLTSI','target']]
df_final.rename(columns={'SEQN':'id','RIDAGEYR':'age_years',
                            'LBDHDDSI':'HDL-cholesterol','LBDTCSI':'total-cholesterol',
                            'LBXSUA':'uric-acid',
                            'DR1TKCAL':'Kcal-intake',
                            'LBDNENO':'segmented-neutrophils',
                            'DR1TCALC':'calcium-intake',
                            'LBDMONO':'Monocyte-number','LBDLYMNO':'Lymphocyte-number',
                            'LBDEONO':'Eosinophils-number','DR2TFIBE':'Fiber-intake',
                            'LBXSATSI':'ALT','LBXSASSI':'AST','LBDSTPSI':'total-protein',
                            'LBDSALSI':'albumin','LBXSTB':'total-bilurubin','LBXHGB':'Hemoglobin',
                            'LBXHCT':'Hydroxycotinine','LBXRBCSI':'red-blood-cells',
                            'LBXMCVSI':'MCV','LBXMCHSI':'MCH','LBXMC':'MCH-conc',
                            'LBXWBCSI':'white-blood-cells',
                            'LBDSIRSI':'iron','LBXPLTSI':'platelet-count'
                           },inplace=True)

df_final
# This will keep only rows which have nan's less than 6 in the dataframe, 
# and will remove all having nan's > 6.
df_final = df_final[df_final.isnull().sum(axis=1) <= 6]

for col in df_final.columns:
    df_final[col] = df_final[col].fillna(df_final[col].mean())

#separem el dataset amb els casos de cardiovascular disease i els que no
df_cvd = df_final[df_final['target']==1]
df_no_cvd = df_final[df_final['target']==0]

X = df_no_cvd.iloc[:,1:27].values

C:\Users\alex.padros\AppData\Local\Temp\12\ipykernel_11000\2188735566.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final.rename(columns={'SEQN':'id','RIDAGEYR':'age_years',

In [5]:
df_cvd

,id,age_years,diastolic-BP,HDL-cholesterol,Kcal-intake,segmented-neutrophils,systolic-BP,calcium-intake,Monocyte-number,Lymphocyte-number,...,Hemoglobin,Hydroxycotinine,red-blood-cells,MCV,MCH,MCH-conc,white-blood-cells,iron,platelet-count,target
0,73557,69,74.000000,1.68,1574.000000,2.0,112.666667,949.0000,0.5,2.0,...,15.2,45.4,5.09,89.3,29.9,33.4,4.7,10.4,204.0,1
4,73562,56,82.000000,0.98,1785.000000,6.5,157.333333,1156.0000,0.6,1.6,...,14.2,41.5,4.93,84.1,28.8,34.2,9.4,9.3,249.0,1
10,73571,76,68.000000,1.29,1076.000000,3.0,126.000000,292.0000,0.5,1.6,...,14.5,43.4,4.85,89.4,30.0,33.5,5.4,11.6,181.0,1
30,73614,55,68.666667,1.09,1142.000000,5.6,107.333333,289.0000,0.8,1.8,...,16.2,48.7,4.77,102.2,34.0,33.2,8.5,12.7,208.0,1
40,73628,80,53.333333,2.51,1972.000000,5.5,108.666667,750.0000,1.0,1.8,...,14.5,41.8,4.66,89.8,31.2,34.7,8.6,16.5,175.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5701,83615,80,66.000000,1.14,1831.000000,5.2,116.000000,785.0000,0.8,1.6,...,16.5,47.4,5.11,92.7,32.2,34.8,7.8,17.9,267.0,1
5706,83623,80,66.666667,1.06,1732.000000,3.3,110.666667,769.0000,0.5,1.3,...,12.6,37.0,4.33,85.6,29.1,34.1,5.2,6.8,159.0,1
5730,83663,72,53.333333,0.93,1106.000000,5.9,116.000000,537.0000,0.6,1.3,...,11.4,32.5,3.49,93.2,32.8,35.3,8.1,10.2,355.0,1
5742,83687,70,68.000000,1.01,2115.028253,3.3,142.000000,928.9437,0.5,1.1,...,14.1,41.6,4.60,90.5,30.7,34.0,5.2,13.3,207.0,1
5754,83708,64,72.666667,0.91,2383.000000,5.0,96.666667,2418.0000,0.6,2.1,...,16.8,48.1,5.45,88.2,30.7,34.7,8.1,13.6,175.0,1

In [6]:
df_no_cvd

,id,age_years,diastolic-BP,HDL-cholesterol,Kcal-intake,segmented-neutrophils,systolic-BP,calcium-intake,Monocyte-number,Lymphocyte-number,...,Hemoglobin,Hydroxycotinine,red-blood-cells,MCV,MCH,MCH-conc,white-blood-cells,iron,platelet-count,target
1,73558,54,61.333333,1.29,5062.0,7.4,157.333333,3193.0,1.0,3.4,...,11.9,36.7,3.84,95.4,31.0,32.5,12.6,14.1,314.0,0
2,73559,72,82.000000,1.55,1743.0,4.9,142.000000,877.0,0.8,1.0,...,17.2,49.9,5.53,90.5,31.1,34.3,7.2,17.6,237.0,0
3,73561,73,86.666667,2.20,1421.0,4.5,137.333333,1410.0,0.5,1.4,...,14.5,43.8,4.72,92.8,30.6,33.0,6.6,16.3,300.0,0
5,73564,61,80.666667,1.50,2585.0,3.0,122.666667,775.0,0.3,1.6,...,13.5,39.8,4.66,85.1,28.8,33.8,5.2,12.7,180.0,0
7,73566,56,72.666667,1.53,1580.0,5.5,122.000000,1125.0,0.7,3.0,...,14.3,41.4,4.43,93.5,32.3,34.6,9.5,6.4,296.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5763,83721,52,72.666667,1.42,1225.0,4.4,109.333333,871.0,0.6,1.4,...,14.4,41.9,4.48,93.6,32.2,34.4,6.8,16.1,152.0,0
5764,83723,61,64.000000,1.27,2181.0,3.9,140.000000,1414.0,0.8,2.9,...,14.3,40.1,4.05,99.2,35.2,35.5,7.7,15.8,181.0,0
5765,83724,80,67.333333,1.32,2432.0,4.2,166.666667,1068.0,0.6,1.2,...,11.8,34.8,3.72,93.8,31.8,33.9,6.1,15.0,180.0,0
5767,83727,26,72.666667,1.42,4687.0,2.9,112.666667,3352.0,0.3,1.6,...,14.9,45.1,5.07,88.9,29.3,32.9,5.1,13.1,226.0,0
5768,83729,42,81.333333,1.24,2475.0,3.2,134.666667,1431.0,0.6,2.5,...,12.2,37.1,4.16,89.1,29.2,32.8,6.4,8.8,213.0,0